### ISSUE TITLE
Steam Deck Usage Unclear

### ISSUE THREAD

**Issue by tidman5** [Lyall/StarTrekResurgenceFix#2]
In your instructions for use on the Steam deck, you say to set the Steam launch options to 
>WINEDLLOVERRIDES="winmm.dll=n,b" %command%.

Is this in the launch options for the Epic store or is there some way to add the Star Trek Resurgence Executable to the Steam library?

**Comment by Lyall** [comment]
So I should preface this by saying that I haven't actually tried this out on the Deck yet. The instructions are just generic for making sure that Ultimate ASI loader is correctly injected when playing the game on Linux. 

I believe you should be able to either add it add a non-steam game and use launch options there. Or you could use something like Heroic Launcher and edit the launch options through that.

When I get a chance tomorrow I'll break out my own Deck and see if I can get the game running. After that I'll post more correct/detailed instructions here.

**Comment by bsilver2988** [comment]
Just wanted to second this issue. I installed via heroic and then run via steam game mode by having heroic add the game to steam. Game actually runs pretty well stock after increasing swap size and vram. However, I'm not sure how  to specify the winedlloverride. I added it to game options in heroic but it doesn't seem to take when opening from steam game mode (which calls the game via heroic command). At least I don't think it's working. Field of view is disabled in the .ini file but background is still blurry in cutscenes.

**Comment by Lyall** [comment]
Okay, sorry for the delay. Here is a rough guide on how to get it working:

1. Install Heroic Launcher. You can get this through the discover app store in desktop mode on the Steam Deck.
2. Login to your Epic account on Heroic.
3. Install the game.
4. Find the game in your library and click on the settings icon.
5. Go down to and expand the "Other" section.
6. Look for "Environment Variables".
7. Enter on the left side `WINEDLLOVERRIDES`.
8. Enter on the right side `winmm.dll=n,b`
9. Click the plus on the right side to add it.
10. Click on the "WINETRICKS" button.
11. Click ok to select the default winetricks.
12. Select "Install a Windows DLL or component" and click OK.
13. Scroll down and tick "vcrun2022" then click OK.
14. Once you are back at the winetricks menu click cancel to close it.
15. Add the game to Steam by clicking the 3 dots menu and choosing "Add to Steam".
16. Play the game.

Unfortunately you'll only know if it worked by checking in-game. For some reason the log files do not get generated on Linux, perhaps some sort of issue with writing files.

**Comment by bsilver2988** [comment]
@Lyall this worked. Thank you!
