### ISSUE TITLE
No hair or eyes and very dark in Linux

### ISSUE THREAD

**Issue by niltooth** [Lyall/StarTrekResurgenceFix#6]
I've applied all the settings and patch from here. I do notice a difference after patching with fps and some video effects. But I can't play because it is so dark and nobody has hair or eyes. Any ideas?

**Comment by Lyall** [comment]
Do you notice these visual issues without the fix installed?

**Comment by Lyall** [comment]
Not too sure what you could try. I'm still relatively new to the world of Linux gaming as my main exposure is through the Steam Deck. Perhaps it would be worth trying with the latest [Proton-GE](https://github.com/GloriousEggroll/proton-ge-custom) version? There's no entry for the game on ProtonDB sadly so it's hard to find out if any one else is running in to the same issues you are seeing.

**Comment by adolfintel** [comment]
It renders correctly for me on Linux, with or without the mod. It runs quite poorly though but I think that's just how this game is and I don't want to install windows just to find out.

I'm using the latest version of Wine-GE-Proton with VKD3D-Proton built from source and Mesa 23.3 also built from source.

<del>@Lyall I'm not sure if Heroic handles things differently, but I think you have a typo in your instructions, it should be `WINEDLLOVERRIDES="winmm=n,b"`, without the .dll.</del> Nevermind, it looks like it accepts both

**Comment by niltooth** [comment]
this is fixed for me now. can close
