### ISSUE TITLE
Trying to get proper scale on Dell U4025QW (native 5120x2160)

### ISSUE THREAD

**Issue by rogersmj** [Lyall/StarTrekResurgenceFix#9]
I have a 5120x2160 monitor on a 4070 Ti and I'm struggling to get this game to run properly scaled. I've installed this fix but none of the resolution options are the right aspect ratio.

For example, the only 1440p options are 2560x1440 and 1920x1440. There's no 3480x1440. As a result, everything winds up being stretched.

The only proper aspect ratio option is native (5120x2160) but then of course I run into the bug where the game runs at about 3fps.

Is there some way to get a ~1440p resolution option with the proper aspect ratio?

**Comment by Lyall** [comment]
If you're on an Nvidia card, your best bet is probably to add a custom resolution in the Nvidia control panel. If your display is 5120x2160, then you'd want a custom resolution of 3840x1620 for the exact same aspect ratio.

![image](https://github.com/user-attachments/assets/8546543b-e24d-4040-95c3-0764ce6627f9)

**Comment by rogersmj** [comment]
Thanks for the suggestion...unfortunately I wasn't able to use the Nvidia control panel to do it, but someone helped me by suggesting a registry edit here: https://www.reddit.com/r/ultrawidemasterrace/comments/1fjf4xq/cant_add_custom_resolutions_via_nvidia_control/
